### ISSUE TITLE
variants & consensus "doing the same thing" ?

### ISSUE THREAD

**Issue by tseemann** [andersen-lab/ivar#14]
Are the `variants` and `consensus` tools doing a lot of similar work, or am I missing something?

At first I assume it was trim -> variants -> consensus but then it seems they are independent?

Are indels handled ok?

PS. trim and consensus are exactly the tools i needed, and i am so grateful this exists!

**Comment by gkarthik** [comment]
You are correct! Under the hood, `variants` and `consensus` do the same allele counting except the `consensus` command takes **indels into account and computes the right consensus for all the downstream positions**. Although the `variants` command does other things like compute amino acid translation given CDS regions in a GFF3 file. 

`variants` and `consensus` are independent of each other. There's no need to take the output of variants to use in the consensus calling. Since we primarily deal with relatively smaller viral sequences, I haven't invested the time to add multi threading but that is on my TODO list. 

I'm really glad you like the tool :D !! We're using it regularly within our lab and I'm actively developing it. I also appreciate the time and effort you've taken to report issues.
