### ISSUE TITLE
Indels that not met minimum requierements called in consensus 

### ISSUE THREAD

**Issue by GaloGS** [andersen-lab/ivar#43]
**Describe the bug**
Hi I think Ivar (v1.2) is adding to consensus indels that do not meet the requirements set by user.

In a sample with an insertion in the consensus genome, when I see that insertion in the tsv file, it has 52% freq. However I have set minimum freq of 70% for consensus calling. 

This happened for several other samples.

However not all insertions are added to the consensus.
For example, in another sample I saw the expected behavior. That sample had many indels in the tsv file, with the PASS flag, but only one, with 82% freq (thus passing the 70% threshold) was included in the consensus.

**Comment by gkarthik** [comment]
Hello, in order to call a consensus for a position with 70% threshold, `ivar consensus` will consider the minimum number of variants in decreasing order of variant frequency that cross the set threshold.

For example,

Consider a position with 2 variants, an insertion at 52% and a SNV at 20%. 
If the minimum frequency threshold for consensus is set at 70%, then a consensus with both the insertions and SNV is called. If the threshold is set at 50% then only the insertion is considered. 

There are also some examples in the [manual](https://andersen-lab.github.io/ivar/html/manualpage.html#autotoc_md19) that might be useful. Hopefully I haven't misunderstood your question and this answers it. Please let me know!

**Comment by MaestSi** [comment]
Hi,
I am writing here since I am facing a similar issue. In particular, I have a position with INDEL frequency 40% and the remaining 60% of the bases are reference. However, the INDEL is inserted in the consensus sequency, despite testing different values of -t parameter. Why do you think this is happening? I read the manual, but I didn't find any examples with INDELs.
Thanks,
Simone

**Comment by gkarthik** [comment]
Could you please use `-q 0`. It is possible that the quality threshold is changing the frequency.

**Comment by MaestSi** [comment]
Ok, I’ll try it out and let you know. However, is -t parameter expected to have any effects on low frequency indels or not?
Thanks

**Comment by gkarthik** [comment]
The `-t` parameter will influence the consensus genome and it takes into account frequency thresholds but it will not influence the frequencies directly.

**Comment by MaestSi** [comment]
Hi, I verified that with -q0, the INS is there in the consensus with -t 0.6 but not with -t 0.1 Could please elaborate a little bit about ivar behaviour in case of low frequency INDELs? I was not able to understand it from the manual.
Thanks

**Comment by gkarthik** [comment]
With `-t 0.1`, your consensus threshold is 10%. So the major variant probably exceed this threshold and the indel is not called in the consensus. At `-t 0.6` (consensus threshold 60%), the majority variant and the indel frequencies must be summed up to cross this threshold which is why the indel is called in the consensus.
