### ISSUE TITLE
Document handling of overlapping primer pairs

### ISSUE THREAD

**Issue by wm75** [andersen-lab/ivar#49]
I tried to find best-practice instructions for dealing with overlapping primer pairs like the ones found in the [Artic V3 primer scheme for SARS-CoV-2](https://github.com/artic-network/artic-ncov2019/tree/master/primer_schemes/nCoV-2019/V3), but couldn't really work it out.

In a case like this:

```
MN908947.3	4054	4077	nCoV-2019_14_LEFT	60	+
MN908947.3	4044	4068	nCoV-2019_14_LEFT_alt4	60	+
MN908947.3	4428	4450	nCoV-2019_14_RIGHT	60	-
MN908947.3	4402	4424	nCoV-2019_14_RIGHT_alt2	60	-
```

which primers will the current version of ivar (1.2.2) trim? All of them? The first it encounters in the BED file? The inner/outermost pair?
I found #18, but I don't understand how a change in the ivar tests ([f274d3a](https://github.com/andersen-lab/ivar/commit/f274d3ad305aa16ff6dc5b38ad2e53fd3235bdd7)) is supposed to affect this.

Similarly for `ivar getmasked` and `ivar removereads`: how should a set of primers like the above be translated into a proper tsv of *primer pairs*? My feeling would be that you want to remove reads for which binding of any of the primers involved in their generation was affected by a variant, but what would be the closest approximation of expressing this in terms of primer pairs?

Any hints would be appreciated :heart:

**Comment by gkarthik** [comment]
Hello! Starting with `v1.2`, ivar handles overlapping primers by taking minimum of start pos of primers for reverse reads and maximum of end position of primers for forward reads. So it ensures that in case of overlapping primers, the innermost sequence is taken. 

I've been busy with other work so haven't been able to get to issues on ivar but will try to document some of the changes!

**Comment by gkarthik** [comment]
`getmasked` and `removereads` are applicable when you see that the primer sequence has a mismatch with the consensus genome which AFAIK, we haven't encountered yet so shouldn't be a necessity. In the primer pairs file, adding `nCoV-2019_14_LEFT_alt4` and `nCoV-2019_14_RIGHT_alt2` as a pair should work but if a NextEra step is used (random tagmentation), I have to write some more checks to check for reads that fall between primer sequences.

**Comment by wm75** [comment]
Thanks for the information, it's highly appreciated!

So if I understand you correctly, in the example, ivar trim would:
- soft-clip `LEFT` *and* `LEFT_alt4` from forward and `RIGHT` *and* `RIGHT_alt2` from reverse reads leaving only non-primer sequence behind as intended.
- for fw reads containing both `LEFT` and `LEFT_alt4`, it would record `LEFT` as the trimmed primer (because it has the higher end position)?
- for rv reads containing both `RIGHT` and `RIGHT_alt2`, it would record  `RIGHT_alt2` (lower start position)?

If the above is true, wouldn't you need to pass *all* of the following primer pairs to `getmasked`:
- `LEFT`/`RIGHT_alt2` (to remove also `RIGHT_alt2` reads if `LEFT` is affected and vice versa)
- `LEFT_alt4`/`RIGHT_alt2` (to remove also `RIGHT_alt2` reads if `LEFT_alt4` is affected)
- `RIGHT`/`LEFT` (to remove also `LEFT` reads if `RIGHT` is affected)
?
but would such a "chain" of pairs even be handled correctly by ivar?

**Comment by gkarthik** [comment]
Hello, yes the trimming you explained here is correct. 

In order to remove reads, `ivar` will only look for one primer per read (1 primer will be recorded for forward and one for reverse). So there would be no need to pass all possible "pairs". 

However, just to reiterate, if there is a NextEra step, this would be more complicated and I'll have to write a check for reads that start between the primers as well. Unfortunately, given my current timeline, not able to really figure out when I would be able to get that done 😔

**Comment by wm75** [comment]
Thanks for confirming some of my reasoning :)

> In order to remove reads, `ivar` will only look for one primer per read (1 primer will be recorded for forward and one for reverse). So there would be no need to pass all possible "pairs".

I think I understood that part, and you *almost* convinced me, but:

Imagine, with the above primer quadruple, you find a variant affecting the binding of `LEFT_alt4`.
This primer would *not* have been recorded by *ivar trim* for any read (only `LEFT` would have been). Still, you'd want to remove all reads, for which `LEFT` and `RIGHT_alt2` have been recorded because `LEFT_alt4` was involved in their nested amplification, wouldn't you?
Same in the case of a variant affecting the binding of `RIGHT`.

So, in addition, to my (incomplete) pairs list above I think you would also like to declare:
- `LEFT_alt4`/`LEFT`
- `RIGHT`/`RIGHT_alt2`

Sorry for being so persistent here.
I agree, the impact of doing or not doing this correctly will probably be modest, and you first need to have a variant affecting one of the nested primers.
However, we're currently working on including Artic/ivar workflows for Galaxy in https://covid19.galaxyproject.org/ and on the major public Galaxy instances, and I really would like to make sure we're delivering high-quality workflows to our users there.

**Comment by gkarthik** [comment]
Hey! To account for overlapping primers, given a position, `ivar getmasked` will output all the primers and the respective pairs ( after 97ad2080599e9c7c031d43fdee19f5ef9f4fde50 ) that contain that position. 

If you consider the following pairs, 
```
LEFT         RIGHT
LEFT_alt4    RIGHT_alt2
```

and a variant is found in position that overlaps LEFT and LEFT_alt4, reads that were trimmed because of any of the 4 primers will be removed, since `getmasked` will output,
```
LEFT    RIGHT    LEFT_alt4    RIGHT_alt2
``` 

However, as of now, this command does NOT remove reads that start in between the forward and reverse primer regions. I plan to incorporate this once my schedule clears up. Another point to note is that while this works well for _invitro_ experiments as described in the [paper](https://doi.org/10.1186/s13059-018-1618-7), in an outbreak scenario like Zika or West Nile (Not SARS-CoV-2 so far), there might be mismatches to multiple primers and hence, you end up losing a lot of the genome by removing reads. In addition, there is a distinct possibility that the variant in the primer site is not linked to variants found in other regions of the amplicon, in which case, the iSNV frequency will not be affected by the primer mismatch. There's some code I'm writing to account for some of this but listing it here to keep in mind for pipelining. 

Thank you for your work on the Galaxy workflows! Happy to help in anyway possible!
